# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weblogic_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1081, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.label_70 = QtWidgets.QLabel(self.tab_15)
        self.label_70.setGeometry(QtCore.QRect(20, 10, 51, 20))
        self.label_70.setObjectName("label_70")
        self.lineEdit_windows_ip = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_windows_ip.setGeometry(QtCore.QRect(70, 10, 261, 20))
        self.lineEdit_windows_ip.setObjectName("lineEdit_windows_ip")
        self.label_71 = QtWidgets.QLabel(self.tab_15)
        self.label_71.setGeometry(QtCore.QRect(350, 10, 61, 21))
        self.label_71.setObjectName("label_71")
        self.lineEdit_windows_port = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_windows_port.setGeometry(QtCore.QRect(410, 10, 141, 20))
        self.lineEdit_windows_port.setObjectName("lineEdit_windows_port")
        self.label_72 = QtWidgets.QLabel(self.tab_15)
        self.label_72.setGeometry(QtCore.QRect(10, 45, 71, 31))
        self.label_72.setObjectName("label_72")
        self.lineEdit_windows_cmd = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_windows_cmd.setGeometry(QtCore.QRect(70, 50, 481, 20))
        self.lineEdit_windows_cmd.setObjectName("lineEdit_windows_cmd")
        self.comboBox_windows_comboBox = QtWidgets.QComboBox(self.tab_15)
        self.comboBox_windows_comboBox.setGeometry(QtCore.QRect(620, 40, 151, 40))
        self.comboBox_windows_comboBox.setObjectName("comboBox_windows_comboBox")
        self.comboBox_windows_comboBox.addItem("")
        self.comboBox_windows_comboBox.addItem("")
        self.label_73 = QtWidgets.QLabel(self.tab_15)
        self.label_73.setGeometry(QtCore.QRect(560, 45, 71, 31))
        self.label_73.setObjectName("label_73")
        self.plainTextEdit_windows_result = QtWidgets.QPlainTextEdit(self.tab_15)
        self.plainTextEdit_windows_result.setGeometry(QtCore.QRect(10, 100, 1051, 671))
        self.plainTextEdit_windows_result.setReadOnly(True)
        self.plainTextEdit_windows_result.setObjectName("plainTextEdit_windows_result")
        self.pushButton_windows_scan = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_windows_scan.setGeometry(QtCore.QRect(780, 45, 91, 32))
        self.pushButton_windows_scan.setObjectName("pushButton_windows_scan")
        self.pushButton_windows_exe = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_windows_exe.setGeometry(QtCore.QRect(870, 45, 91, 32))
        self.pushButton_windows_exe.setObjectName("pushButton_windows_exe")
        self.tabWidget.addTab(self.tab_15, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit_weblogic_result = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_weblogic_result.setGeometry(QtCore.QRect(10, 130, 1061, 621))
        self.plainTextEdit_weblogic_result.setReadOnly(True)
        self.plainTextEdit_weblogic_result.setObjectName("plainTextEdit_weblogic_result")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 21, 475, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_weblogic_ip = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_weblogic_ip.setObjectName("lineEdit_weblogic_ip")
        self.horizontalLayout.addWidget(self.lineEdit_weblogic_ip)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_weblogic_port = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_weblogic_port.setObjectName("lineEdit_weblogic_port")
        self.horizontalLayout.addWidget(self.lineEdit_weblogic_port)
        self.pushButton_weblogic_start = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_weblogic_start.setObjectName("pushButton_weblogic_start")
        self.horizontalLayout.addWidget(self.pushButton_weblogic_start)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(3, 84, 65, 18))
        self.label_23.setObjectName("label_23")
        self.comboBox_weblogic_bug = QtWidgets.QComboBox(self.tab)
        self.comboBox_weblogic_bug.setGeometry(QtCore.QRect(73, 82, 153, 26))
        self.comboBox_weblogic_bug.setObjectName("comboBox_weblogic_bug")
        self.comboBox_weblogic_bug.addItem("")
        self.comboBox_weblogic_bug.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(233, 84, 65, 18))
        self.label_3.setObjectName("label_3")
        self.lineEdit_weblogic_cmd = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_weblogic_cmd.setGeometry(QtCore.QRect(306, 84, 251, 21))
        self.lineEdit_weblogic_cmd.setObjectName("lineEdit_weblogic_cmd")
        self.pushButton_weblogic_exe = QtWidgets.QPushButton(self.tab)
        self.pushButton_weblogic_exe.setGeometry(QtCore.QRect(570, 80, 94, 32))
        self.pushButton_weblogic_exe.setObjectName("pushButton_weblogic_exe")
        self.pushButton_weblogic_uploadshell = QtWidgets.QPushButton(self.tab)
        self.pushButton_weblogic_uploadshell.setGeometry(QtCore.QRect(670, 80, 97, 32))
        self.pushButton_weblogic_uploadshell.setObjectName("pushButton_weblogic_uploadshell")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 211, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(21, 65, 55, 18))
        self.label_7.setObjectName("label_7")
        self.lineEdit_struts2_url = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_struts2_url.setEnabled(True)
        self.lineEdit_struts2_url.setGeometry(QtCore.QRect(84, 65, 661, 21))
        self.lineEdit_struts2_url.setObjectName("lineEdit_struts2_url")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(21, 96, 53, 18))
        self.label_8.setObjectName("label_8")
        self.lineEdit_struts2_cookie = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_struts2_cookie.setGeometry(QtCore.QRect(84, 96, 661, 21))
        self.lineEdit_struts2_cookie.setObjectName("lineEdit_struts2_cookie")
        self.pushButton_struts2_scan = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_struts2_scan.setGeometry(QtCore.QRect(760, 60, 83, 32))
        self.pushButton_struts2_scan.setObjectName("pushButton_struts2_scan")
        self.plainTextEdit_struts2_result = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_struts2_result.setGeometry(QtCore.QRect(10, 170, 1061, 581))
        self.plainTextEdit_struts2_result.setReadOnly(True)
        self.plainTextEdit_struts2_result.setObjectName("plainTextEdit_struts2_result")
        self.comboBox_strust2_bug = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_strust2_bug.setGeometry(QtCore.QRect(505, 132, 160, 26))
        self.comboBox_strust2_bug.setObjectName("comboBox_strust2_bug")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.comboBox_strust2_bug.addItem("")
        self.pushButton_struts2_exe = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_struts2_exe.setGeometry(QtCore.QRect(670, 130, 81, 32))
        self.pushButton_struts2_exe.setObjectName("pushButton_struts2_exe")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 134, 65, 18))
        self.label_10.setObjectName("label_10")
        self.lineEdit_struts2_cmd = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_struts2_cmd.setGeometry(QtCore.QRect(84, 134, 341, 21))
        self.lineEdit_struts2_cmd.setObjectName("lineEdit_struts2_cmd")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(435, 134, 65, 18))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_jboss_scan = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_jboss_scan.setGeometry(QtCore.QRect(660, 43, 113, 32))
        self.pushButton_jboss_scan.setObjectName("pushButton_jboss_scan")
        self.label_121 = QtWidgets.QLabel(self.tab_13)
        self.label_121.setGeometry(QtCore.QRect(20, 87, 60, 16))
        self.label_121.setObjectName("label_121")
        self.label_122 = QtWidgets.QLabel(self.tab_13)
        self.label_122.setGeometry(QtCore.QRect(30, 50, 60, 16))
        self.label_122.setObjectName("label_122")
        self.lineEdit_jboss_url = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_jboss_url.setGeometry(QtCore.QRect(60, 48, 591, 21))
        self.lineEdit_jboss_url.setObjectName("lineEdit_jboss_url")
        self.comboBox_jboss_cve = QtWidgets.QComboBox(self.tab_13)
        self.comboBox_jboss_cve.setGeometry(QtCore.QRect(740, 83, 171, 26))
        self.comboBox_jboss_cve.setObjectName("comboBox_jboss_cve")
        self.comboBox_jboss_cve.addItem("")
        self.pushButton_jboss_exe = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_jboss_exe.setGeometry(QtCore.QRect(920, 80, 71, 32))
        self.pushButton_jboss_exe.setObjectName("pushButton_jboss_exe")
        self.pushButton_jboss_urllist = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_jboss_urllist.setGeometry(QtCore.QRect(490, 5, 81, 32))
        self.pushButton_jboss_urllist.setObjectName("pushButton_jboss_urllist")
        self.label_123 = QtWidgets.QLabel(self.tab_13)
        self.label_123.setGeometry(QtCore.QRect(670, 87, 60, 16))
        self.label_123.setObjectName("label_123")
        self.lineEdit_jboss_cmd = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_jboss_cmd.setGeometry(QtCore.QRect(60, 85, 591, 21))
        self.lineEdit_jboss_cmd.setObjectName("lineEdit_jboss_cmd")
        self.lineEdit_jboss_urllist = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_jboss_urllist.setGeometry(QtCore.QRect(580, 10, 461, 21))
        self.lineEdit_jboss_urllist.setObjectName("lineEdit_jboss_urllist")
        self.plainTextEdit_jboss_result = QtWidgets.QPlainTextEdit(self.tab_13)
        self.plainTextEdit_jboss_result.setGeometry(QtCore.QRect(10, 120, 1051, 631))
        self.plainTextEdit_jboss_result.setReadOnly(True)
        self.plainTextEdit_jboss_result.setObjectName("plainTextEdit_jboss_result")
        self.lineEdit_jboss_jar = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_jboss_jar.setGeometry(QtCore.QRect(170, 10, 311, 21))
        self.lineEdit_jboss_jar.setObjectName("lineEdit_jboss_jar")
        self.pushButton_jboss_ysoserialpath = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_jboss_ysoserialpath.setGeometry(QtCore.QRect(20, 5, 141, 32))
        self.pushButton_jboss_ysoserialpath.setObjectName("pushButton_jboss_ysoserialpath")
        self.pushButton_jboss_clearlog = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_jboss_clearlog.setGeometry(QtCore.QRect(990, 80, 71, 32))
        self.pushButton_jboss_clearlog.setObjectName("pushButton_jboss_clearlog")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.label_55 = QtWidgets.QLabel(self.tab_12)
        self.label_55.setGeometry(QtCore.QRect(20, 12, 60, 16))
        self.label_55.setObjectName("label_55")
        self.lineEdit_apache_url = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_apache_url.setGeometry(QtCore.QRect(50, 10, 251, 21))
        self.lineEdit_apache_url.setObjectName("lineEdit_apache_url")
        self.label_59 = QtWidgets.QLabel(self.tab_12)
        self.label_59.setGeometry(QtCore.QRect(10, 42, 60, 16))
        self.label_59.setObjectName("label_59")
        self.lineEdit_apache_cmd = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_apache_cmd.setGeometry(QtCore.QRect(50, 40, 251, 21))
        self.lineEdit_apache_cmd.setObjectName("lineEdit_apache_cmd")
        self.comboBox_apache_cve = QtWidgets.QComboBox(self.tab_12)
        self.comboBox_apache_cve.setGeometry(QtCore.QRect(830, 7, 141, 26))
        self.comboBox_apache_cve.setObjectName("comboBox_apache_cve")
        self.comboBox_apache_cve.addItem("")
        self.label_60 = QtWidgets.QLabel(self.tab_12)
        self.label_60.setGeometry(QtCore.QRect(760, 12, 60, 16))
        self.label_60.setObjectName("label_60")
        self.pushButton_apache_scan = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_apache_scan.setGeometry(QtCore.QRect(640, 5, 113, 32))
        self.pushButton_apache_scan.setObjectName("pushButton_apache_scan")
        self.pushButton_apache_exe = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_apache_exe.setGeometry(QtCore.QRect(300, 35, 113, 32))
        self.pushButton_apache_exe.setObjectName("pushButton_apache_exe")
        self.plainTextEdit_apache_result = QtWidgets.QPlainTextEdit(self.tab_12)
        self.plainTextEdit_apache_result.setGeometry(QtCore.QRect(10, 70, 1051, 681))
        self.plainTextEdit_apache_result.setReadOnly(True)
        self.plainTextEdit_apache_result.setObjectName("plainTextEdit_apache_result")
        self.lineEdit_apache_urllist = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_apache_urllist.setGeometry(QtCore.QRect(380, 10, 251, 21))
        self.lineEdit_apache_urllist.setObjectName("lineEdit_apache_urllist")
        self.pushButton_apache_selectfile = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_apache_selectfile.setGeometry(QtCore.QRect(300, 5, 81, 32))
        self.pushButton_apache_selectfile.setObjectName("pushButton_apache_selectfile")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_16)
        self.tabWidget_2.setGeometry(QtCore.QRect(-30, 0, 1101, 751))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.label_74 = QtWidgets.QLabel(self.tab_18)
        self.label_74.setGeometry(QtCore.QRect(55, 10, 41, 20))
        self.label_74.setObjectName("label_74")
        self.lineEdit_tomcat_2020_1938_ip = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_tomcat_2020_1938_ip.setGeometry(QtCore.QRect(110, 10, 571, 21))
        self.lineEdit_tomcat_2020_1938_ip.setObjectName("lineEdit_tomcat_2020_1938_ip")
        self.label_75 = QtWidgets.QLabel(self.tab_18)
        self.label_75.setGeometry(QtCore.QRect(700, 12, 60, 16))
        self.label_75.setObjectName("label_75")
        self.lineEdit_tomcat_2020_1938_port = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_tomcat_2020_1938_port.setGeometry(QtCore.QRect(740, 10, 91, 21))
        self.lineEdit_tomcat_2020_1938_port.setObjectName("lineEdit_tomcat_2020_1938_port")
        self.label_76 = QtWidgets.QLabel(self.tab_18)
        self.label_76.setGeometry(QtCore.QRect(40, 70, 81, 16))
        self.label_76.setObjectName("label_76")
        self.lineEdit_tomcat_2020_1938_file_path = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_tomcat_2020_1938_file_path.setGeometry(QtCore.QRect(110, 70, 571, 21))
        self.lineEdit_tomcat_2020_1938_file_path.setObjectName("lineEdit_tomcat_2020_1938_file_path")
        self.pushButton_tomcat_2020_1938_read_file = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_tomcat_2020_1938_read_file.setGeometry(QtCore.QRect(690, 65, 111, 32))
        self.pushButton_tomcat_2020_1938_read_file.setObjectName("pushButton_tomcat_2020_1938_read_file")
        self.plainTextEdit_tomcat_2020_1938_result = QtWidgets.QPlainTextEdit(self.tab_18)
        self.plainTextEdit_tomcat_2020_1938_result.setGeometry(QtCore.QRect(40, 120, 1041, 631))
        self.plainTextEdit_tomcat_2020_1938_result.setReadOnly(True)
        self.plainTextEdit_tomcat_2020_1938_result.setObjectName("plainTextEdit_tomcat_2020_1938_result")
        self.label_77 = QtWidgets.QLabel(self.tab_18)
        self.label_77.setGeometry(QtCore.QRect(30, 40, 71, 20))
        self.label_77.setObjectName("label_77")
        self.lineEdit_tomcat_2020_1938_ip_list = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_tomcat_2020_1938_ip_list.setGeometry(QtCore.QRect(110, 40, 571, 21))
        self.lineEdit_tomcat_2020_1938_ip_list.setObjectName("lineEdit_tomcat_2020_1938_ip_list")
        self.pushButton_tomcat_2020_1938_check = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_tomcat_2020_1938_check.setGeometry(QtCore.QRect(760, 36, 71, 32))
        self.pushButton_tomcat_2020_1938_check.setObjectName("pushButton_tomcat_2020_1938_check")
        self.pushButton_tomcat_2020_1938_select_file = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_tomcat_2020_1938_select_file.setGeometry(QtCore.QRect(690, 36, 71, 32))
        self.pushButton_tomcat_2020_1938_select_file.setObjectName("pushButton_tomcat_2020_1938_select_file")
        self.tabWidget_2.addTab(self.tab_18, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.tabWidget_2.addTab(self.tab_17, "")
        self.tabWidget.addTab(self.tab_16, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 471, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(41, 71, 51, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_urlscan_url = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_urlscan_url.setGeometry(QtCore.QRect(100, 71, 721, 21))
        self.lineEdit_urlscan_url.setObjectName("lineEdit_urlscan_url")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(40, 100, 44, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_urlscan_cookie = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_urlscan_cookie.setGeometry(QtCore.QRect(100, 101, 721, 21))
        self.lineEdit_urlscan_cookie.setObjectName("lineEdit_urlscan_cookie")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(30, 130, 101, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_urlscan_dict = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_urlscan_dict.setGeometry(QtCore.QRect(100, 130, 281, 21))
        self.lineEdit_urlscan_dict.setObjectName("lineEdit_urlscan_dict")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(483, 129, 52, 18))
        self.label_15.setObjectName("label_15")
        self.comboBox_urlscan_thread = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_urlscan_thread.setGeometry(QtCore.QRect(540, 127, 61, 26))
        self.comboBox_urlscan_thread.setObjectName("comboBox_urlscan_thread")
        self.comboBox_urlscan_thread.addItem("")
        self.comboBox_urlscan_thread.addItem("")
        self.comboBox_urlscan_thread.addItem("")
        self.comboBox_urlscan_thread.addItem("")
        self.plainTextEdit_urlscan_result = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_urlscan_result.setGeometry(QtCore.QRect(10, 180, 1061, 541))
        self.plainTextEdit_urlscan_result.setReadOnly(True)
        self.plainTextEdit_urlscan_result.setObjectName("plainTextEdit_urlscan_result")
        self.progressBar_urlscan_progress = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_urlscan_progress.setGeometry(QtCore.QRect(10, 720, 1061, 23))
        self.progressBar_urlscan_progress.setProperty("value", 0)
        self.progressBar_urlscan_progress.setObjectName("progressBar_urlscan_progress")
        self.plainTextEdit_urlscan_ignore = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_urlscan_ignore.setGeometry(QtCore.QRect(840, 70, 211, 81))
        self.plainTextEdit_urlscan_ignore.setObjectName("plainTextEdit_urlscan_ignore")
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setGeometry(QtCore.QRect(840, 50, 161, 16))
        self.label_48.setObjectName("label_48")
        self.pushButton_urlscan_choice = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_urlscan_choice.setGeometry(QtCore.QRect(390, 125, 81, 32))
        self.pushButton_urlscan_choice.setObjectName("pushButton_urlscan_choice")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(610, 125, 138, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_urlscan_start = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_urlscan_start.setObjectName("pushButton_urlscan_start")
        self.horizontalLayout_9.addWidget(self.pushButton_urlscan_start)
        self.pushButton_urlscan_stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_urlscan_stop.setObjectName("pushButton_urlscan_stop")
        self.horizontalLayout_9.addWidget(self.pushButton_urlscan_stop)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(97, 42, 24, 18))
        self.label_16.setObjectName("label_16")
        self.lineEdit_brute_ip = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_brute_ip.setGeometry(QtCore.QRect(129, 42, 125, 21))
        self.lineEdit_brute_ip.setObjectName("lineEdit_brute_ip")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(264, 42, 38, 18))
        self.label_17.setObjectName("label_17")
        self.lineEdit_brute_port = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_brute_port.setGeometry(QtCore.QRect(310, 42, 51, 21))
        self.lineEdit_brute_port.setObjectName("lineEdit_brute_port")
        self.plainTextEdit_brute_result = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_brute_result.setGeometry(QtCore.QRect(10, 170, 1061, 581))
        self.plainTextEdit_brute_result.setReadOnly(True)
        self.plainTextEdit_brute_result.setObjectName("plainTextEdit_brute_result")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(580, 40, 250, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(394, 44, 65, 18))
        self.label_18.setObjectName("label_18")
        self.radioButton_brute_ftp = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_brute_ftp.setGeometry(QtCore.QRect(520, 44, 51, 20))
        self.radioButton_brute_ftp.setObjectName("radioButton_brute_ftp")
        self.radioButton_brute_mysql = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_brute_mysql.setGeometry(QtCore.QRect(580, 44, 71, 20))
        self.radioButton_brute_mysql.setObjectName("radioButton_brute_mysql")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(664, 44, 74, 20))
        self.label_19.setObjectName("label_19")
        self.comboBox_brute_thread = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_brute_thread.setGeometry(QtCore.QRect(743, 42, 79, 26))
        self.comboBox_brute_thread.setObjectName("comboBox_brute_thread")
        self.comboBox_brute_thread.addItem("")
        self.comboBox_brute_thread.addItem("")
        self.comboBox_brute_thread.addItem("")
        self.comboBox_brute_thread.addItem("")
        self.radioButton_brute_ssh = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_brute_ssh.setGeometry(QtCore.QRect(465, 44, 51, 20))
        self.radioButton_brute_ssh.setObjectName("radioButton_brute_ssh")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(80, 114, 50, 18))
        self.label_20.setObjectName("label_20")
        self.pushButton_brute_set_iplist = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_brute_set_iplist.setGeometry(QtCore.QRect(140, 110, 107, 32))
        self.pushButton_brute_set_iplist.setObjectName("pushButton_brute_set_iplist")
        self.lineEdit_brute_iplist = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_brute_iplist.setGeometry(QtCore.QRect(260, 114, 121, 21))
        self.lineEdit_brute_iplist.setObjectName("lineEdit_brute_iplist")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(390, 114, 78, 18))
        self.label_21.setObjectName("label_21")
        self.pushButton_brute_set_usernamelist = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_brute_set_usernamelist.setGeometry(QtCore.QRect(460, 110, 107, 32))
        self.pushButton_brute_set_usernamelist.setObjectName("pushButton_brute_set_usernamelist")
        self.lineEdit_brute_usernamelist = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_brute_usernamelist.setGeometry(QtCore.QRect(580, 114, 121, 21))
        self.lineEdit_brute_usernamelist.setObjectName("lineEdit_brute_usernamelist")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(710, 114, 65, 18))
        self.label_22.setObjectName("label_22")
        self.pushButton_brute_set_passwdlist = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_brute_set_passwdlist.setGeometry(QtCore.QRect(770, 110, 107, 32))
        self.pushButton_brute_set_passwdlist.setObjectName("pushButton_brute_set_passwdlist")
        self.lineEdit_brute_passwdlist = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_brute_passwdlist.setGeometry(QtCore.QRect(890, 114, 121, 21))
        self.lineEdit_brute_passwdlist.setObjectName("lineEdit_brute_passwdlist")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(840, 40, 138, 32))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_brute_start = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_brute_start.setObjectName("pushButton_brute_start")
        self.horizontalLayout_10.addWidget(self.pushButton_brute_start)
        self.pushButton_brute_stop = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_brute_stop.setObjectName("pushButton_brute_stop")
        self.horizontalLayout_10.addWidget(self.pushButton_brute_stop)
        self.radioButton_brute_telnet = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_brute_telnet.setGeometry(QtCore.QRect(465, 70, 100, 20))
        self.radioButton_brute_telnet.setObjectName("radioButton_brute_telnet")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.plainTextEdit_portscan_result = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit_portscan_result.setGeometry(QtCore.QRect(10, 70, 1061, 651))
        self.plainTextEdit_portscan_result.setReadOnly(True)
        self.plainTextEdit_portscan_result.setObjectName("plainTextEdit_portscan_result")
        self.progressBar_portscan_progress = QtWidgets.QProgressBar(self.tab_5)
        self.progressBar_portscan_progress.setGeometry(QtCore.QRect(10, 730, 1061, 23))
        self.progressBar_portscan_progress.setProperty("value", 0)
        self.progressBar_portscan_progress.setObjectName("progressBar_portscan_progress")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(16, 20, 962, 33))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_portscan_ip = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_portscan_ip.setObjectName("lineEdit_portscan_ip")
        self.horizontalLayout_2.addWidget(self.lineEdit_portscan_ip)
        self.pushButton_portscan_selectfile = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_portscan_selectfile.setObjectName("pushButton_portscan_selectfile")
        self.horizontalLayout_2.addWidget(self.pushButton_portscan_selectfile)
        self.lineEdit_portscan_file = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_portscan_file.setObjectName("lineEdit_portscan_file")
        self.horizontalLayout_2.addWidget(self.lineEdit_portscan_file)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_portscan_port = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_portscan_port.setObjectName("lineEdit_portscan_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_portscan_port)
        self.radioButton_portscan_radio1000 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_portscan_radio1000.setObjectName("radioButton_portscan_radio1000")
        self.horizontalLayout_2.addWidget(self.radioButton_portscan_radio1000)
        self.radioButton_portscan_radioall = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_portscan_radioall.setObjectName("radioButton_portscan_radioall")
        self.horizontalLayout_2.addWidget(self.radioButton_portscan_radioall)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.comboBox_portscan_thread = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_portscan_thread.setObjectName("comboBox_portscan_thread")
        self.comboBox_portscan_thread.addItem("")
        self.comboBox_portscan_thread.addItem("")
        self.comboBox_portscan_thread.addItem("")
        self.comboBox_portscan_thread.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_portscan_thread)
        self.pushButton_portscan_start = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_portscan_start.setObjectName("pushButton_portscan_start")
        self.horizontalLayout_2.addWidget(self.pushButton_portscan_start)
        self.pushButton_portscan_stop = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_portscan_stop.setGeometry(QtCore.QRect(980, 20, 71, 32))
        self.pushButton_portscan_stop.setObjectName("pushButton_portscan_stop")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plainTextEdit_submain_result = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEdit_submain_result.setGeometry(QtCore.QRect(10, 110, 1061, 611))
        self.plainTextEdit_submain_result.setReadOnly(True)
        self.plainTextEdit_submain_result.setObjectName("plainTextEdit_submain_result")
        self.progressBar_subdomain_progress = QtWidgets.QProgressBar(self.tab_6)
        self.progressBar_subdomain_progress.setGeometry(QtCore.QRect(10, 730, 1061, 23))
        self.progressBar_subdomain_progress.setProperty("value", 0)
        self.progressBar_subdomain_progress.setObjectName("progressBar_subdomain_progress")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(21, 64, 39, 18))
        self.label_28.setObjectName("label_28")
        self.lineEdit_subdomian_dict = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_subdomian_dict.setGeometry(QtCore.QRect(68, 64, 181, 21))
        self.lineEdit_subdomian_dict.setObjectName("lineEdit_subdomian_dict")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(22, 22, 39, 18))
        self.label_25.setObjectName("label_25")
        self.lineEdit_subdomain_domain = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_subdomain_domain.setGeometry(QtCore.QRect(69, 22, 181, 21))
        self.lineEdit_subdomain_domain.setObjectName("lineEdit_subdomain_domain")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(264, 22, 36, 18))
        self.label_26.setObjectName("label_26")
        self.comboBox_subdomain_dns = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_subdomain_dns.setGeometry(QtCore.QRect(305, 20, 152, 26))
        self.comboBox_subdomain_dns.setObjectName("comboBox_subdomain_dns")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.comboBox_subdomain_dns.addItem("")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(464, 22, 75, 18))
        self.label_29.setObjectName("label_29")
        self.lineEdit_subdomain_setdns = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_subdomain_setdns.setGeometry(QtCore.QRect(547, 22, 131, 21))
        self.lineEdit_subdomain_setdns.setObjectName("lineEdit_subdomain_setdns")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(683, 22, 52, 18))
        self.label_27.setObjectName("label_27")
        self.comboBox_subdomain_thread = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_subdomain_thread.setGeometry(QtCore.QRect(740, 20, 68, 26))
        self.comboBox_subdomain_thread.setObjectName("comboBox_subdomain_thread")
        self.comboBox_subdomain_thread.addItem("")
        self.comboBox_subdomain_thread.addItem("")
        self.comboBox_subdomain_thread.addItem("")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget5.setGeometry(QtCore.QRect(250, 60, 208, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_subdomian_selectdict = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_subdomian_selectdict.setObjectName("pushButton_subdomian_selectdict")
        self.horizontalLayout_11.addWidget(self.pushButton_subdomian_selectdict)
        self.pushButton_subdomain_start = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_subdomain_start.setObjectName("pushButton_subdomain_start")
        self.horizontalLayout_11.addWidget(self.pushButton_subdomain_start)
        self.pushButton_subdomain_stop = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_subdomain_stop.setObjectName("pushButton_subdomain_stop")
        self.horizontalLayout_11.addWidget(self.pushButton_subdomain_stop)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.plainTextEdit_unauthorized_data1request = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_unauthorized_data1request.setGeometry(QtCore.QRect(10, 90, 521, 271))
        self.plainTextEdit_unauthorized_data1request.setObjectName("plainTextEdit_unauthorized_data1request")
        self.plainTextEdit_unauthorized_data2request = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_unauthorized_data2request.setGeometry(QtCore.QRect(540, 90, 521, 271))
        self.plainTextEdit_unauthorized_data2request.setObjectName("plainTextEdit_unauthorized_data2request")
        self.plainTextEdit_unauthorized_result = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_unauthorized_result.setGeometry(QtCore.QRect(10, 650, 1051, 91))
        self.plainTextEdit_unauthorized_result.setReadOnly(True)
        self.plainTextEdit_unauthorized_result.setObjectName("plainTextEdit_unauthorized_result")
        self.lineEdit_unauthorized_getparam = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_unauthorized_getparam.setGeometry(QtCore.QRect(68, 1, 551, 21))
        self.lineEdit_unauthorized_getparam.setObjectName("lineEdit_unauthorized_getparam")
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(21, 32, 39, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_unauthorized_postparam = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_unauthorized_postparam.setGeometry(QtCore.QRect(68, 32, 551, 21))
        self.lineEdit_unauthorized_postparam.setObjectName("lineEdit_unauthorized_postparam")
        self.label_32 = QtWidgets.QLabel(self.tab_7)
        self.label_32.setGeometry(QtCore.QRect(10, 63, 53, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_unauthorized_cookieparam = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_unauthorized_cookieparam.setGeometry(QtCore.QRect(70, 63, 551, 21))
        self.lineEdit_unauthorized_cookieparam.setObjectName("lineEdit_unauthorized_cookieparam")
        self.label_30 = QtWidgets.QLabel(self.tab_7)
        self.label_30.setGeometry(QtCore.QRect(21, 1, 30, 16))
        self.label_30.setObjectName("label_30")
        self.plainTextEdit_unauthorized_data1response = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_unauthorized_data1response.setGeometry(QtCore.QRect(10, 370, 521, 271))
        self.plainTextEdit_unauthorized_data1response.setObjectName("plainTextEdit_unauthorized_data1response")
        self.plainTextEdit_unauthorized_data2response = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_unauthorized_data2response.setGeometry(QtCore.QRect(540, 370, 521, 271))
        self.plainTextEdit_unauthorized_data2response.setObjectName("plainTextEdit_unauthorized_data2response")
        self.comboBox_unauthorized_selectcharacteristic = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_unauthorized_selectcharacteristic.setGeometry(QtCore.QRect(840, 30, 221, 26))
        self.comboBox_unauthorized_selectcharacteristic.setObjectName("comboBox_unauthorized_selectcharacteristic")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget6.setGeometry(QtCore.QRect(640, 30, 196, 24))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_unauthorized_vertical = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_unauthorized_vertical.setObjectName("radioButton_unauthorized_vertical")
        self.horizontalLayout_5.addWidget(self.radioButton_unauthorized_vertical)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget7.setGeometry(QtCore.QRect(640, 60, 360, 26))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.comboBox_unauthorized_response1value = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_unauthorized_response1value.setObjectName("comboBox_unauthorized_response1value")
        self.horizontalLayout_6.addWidget(self.comboBox_unauthorized_response1value)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.comboBox_unauthorized_response2value = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_unauthorized_response2value.setObjectName("comboBox_unauthorized_response2value")
        self.horizontalLayout_6.addWidget(self.comboBox_unauthorized_response2value)
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget8.setGeometry(QtCore.QRect(630, 0, 396, 32))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_unauthorized_allparam = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_unauthorized_allparam.setObjectName("pushButton_unauthorized_allparam")
        self.horizontalLayout_3.addWidget(self.pushButton_unauthorized_allparam)
        self.pushButton_unauthorized_clearresult = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_unauthorized_clearresult.setObjectName("pushButton_unauthorized_clearresult")
        self.horizontalLayout_3.addWidget(self.pushButton_unauthorized_clearresult)
        self.pushButton_unauthorized_startallparam = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_unauthorized_startallparam.setObjectName("pushButton_unauthorized_startallparam")
        self.horizontalLayout_3.addWidget(self.pushButton_unauthorized_startallparam)
        self.radioButton_unauthorized_operation = QtWidgets.QRadioButton(self.layoutWidget8)
        self.radioButton_unauthorized_operation.setObjectName("radioButton_unauthorized_operation")
        self.horizontalLayout_3.addWidget(self.radioButton_unauthorized_operation)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.plainTextEdit_xss_request = QtWidgets.QPlainTextEdit(self.tab_8)
        self.plainTextEdit_xss_request.setGeometry(QtCore.QRect(10, 90, 531, 301))
        self.plainTextEdit_xss_request.setObjectName("plainTextEdit_xss_request")
        self.plainTextEdit_xss_result = QtWidgets.QPlainTextEdit(self.tab_8)
        self.plainTextEdit_xss_result.setGeometry(QtCore.QRect(10, 400, 1051, 361))
        self.plainTextEdit_xss_result.setReadOnly(True)
        self.plainTextEdit_xss_result.setObjectName("plainTextEdit_xss_result")
        self.plainTextEdit_xss_payload = QtWidgets.QPlainTextEdit(self.tab_8)
        self.plainTextEdit_xss_payload.setGeometry(QtCore.QRect(550, 90, 511, 301))
        self.plainTextEdit_xss_payload.setReadOnly(True)
        self.plainTextEdit_xss_payload.setObjectName("plainTextEdit_xss_payload")
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget9.setGeometry(QtCore.QRect(11, 30, 773, 32))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_7.addWidget(self.label_36)
        self.comboBox_xss_thread = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_xss_thread.setObjectName("comboBox_xss_thread")
        self.comboBox_xss_thread.addItem("")
        self.comboBox_xss_thread.addItem("")
        self.comboBox_xss_thread.addItem("")
        self.comboBox_xss_thread.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_xss_thread)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_7.addWidget(self.label_37)
        self.comboBox_xss_delay = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_xss_delay.setObjectName("comboBox_xss_delay")
        self.comboBox_xss_delay.addItem("")
        self.comboBox_xss_delay.addItem("")
        self.comboBox_xss_delay.addItem("")
        self.comboBox_xss_delay.addItem("")
        self.comboBox_xss_delay.addItem("")
        self.comboBox_xss_delay.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_xss_delay)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_7.addWidget(self.label_38)
        self.comboBox_xss_skipdom = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_xss_skipdom.setObjectName("comboBox_xss_skipdom")
        self.comboBox_xss_skipdom.addItem("")
        self.comboBox_xss_skipdom.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_xss_skipdom)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_7.addWidget(self.label_39)
        self.comboBox_xss_crawl = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_xss_crawl.setObjectName("comboBox_xss_crawl")
        self.comboBox_xss_crawl.addItem("")
        self.comboBox_xss_crawl.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_xss_crawl)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_7.addWidget(self.label_40)
        self.comboBox_xss_deep = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_xss_deep.setObjectName("comboBox_xss_deep")
        self.comboBox_xss_deep.addItem("")
        self.comboBox_xss_deep.addItem("")
        self.comboBox_xss_deep.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_xss_deep)
        self.pushButton_xss_start = QtWidgets.QPushButton(self.layoutWidget9)
        self.pushButton_xss_start.setObjectName("pushButton_xss_start")
        self.horizontalLayout_7.addWidget(self.pushButton_xss_start)
        self.pushButton_xss_wait = QtWidgets.QPushButton(self.layoutWidget9)
        self.pushButton_xss_wait.setObjectName("pushButton_xss_wait")
        self.horizontalLayout_7.addWidget(self.pushButton_xss_wait)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_61 = QtWidgets.QLabel(self.tab_14)
        self.label_61.setGeometry(QtCore.QRect(40, 12, 101, 16))
        self.label_61.setObjectName("label_61")
        self.lineEdit_sqlmap_apiurl = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_sqlmap_apiurl.setGeometry(QtCore.QRect(140, 10, 501, 21))
        self.lineEdit_sqlmap_apiurl.setObjectName("lineEdit_sqlmap_apiurl")
        self.pushButton_sqlmap_checkenv = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_checkenv.setGeometry(QtCore.QRect(650, 5, 101, 32))
        self.pushButton_sqlmap_checkenv.setObjectName("pushButton_sqlmap_checkenv")
        self.label_62 = QtWidgets.QLabel(self.tab_14)
        self.label_62.setGeometry(QtCore.QRect(0, 42, 141, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_14)
        self.label_63.setGeometry(QtCore.QRect(60, 72, 81, 16))
        self.label_63.setObjectName("label_63")
        self.lineEdit_sqlmap_filepath = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_sqlmap_filepath.setGeometry(QtCore.QRect(140, 40, 501, 21))
        self.lineEdit_sqlmap_filepath.setObjectName("lineEdit_sqlmap_filepath")
        self.lineEdit_sqlmap_sqlshell = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_sqlmap_sqlshell.setGeometry(QtCore.QRect(140, 70, 501, 21))
        self.lineEdit_sqlmap_sqlshell.setObjectName("lineEdit_sqlmap_sqlshell")
        self.pushButton_sqlmap_selectfile = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_selectfile.setGeometry(QtCore.QRect(650, 35, 101, 32))
        self.pushButton_sqlmap_selectfile.setObjectName("pushButton_sqlmap_selectfile")
        self.pushButton_sqlmap_startscan = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_startscan.setGeometry(QtCore.QRect(750, 35, 91, 32))
        self.pushButton_sqlmap_startscan.setObjectName("pushButton_sqlmap_startscan")
        self.pushButton_sqlmap_exesql = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_exesql.setGeometry(QtCore.QRect(650, 65, 101, 32))
        self.pushButton_sqlmap_exesql.setObjectName("pushButton_sqlmap_exesql")
        self.label_64 = QtWidgets.QLabel(self.tab_14)
        self.label_64.setGeometry(QtCore.QRect(10, 110, 60, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_14)
        self.label_65.setGeometry(QtCore.QRect(190, 110, 60, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_14)
        self.label_66.setGeometry(QtCore.QRect(370, 110, 60, 16))
        self.label_66.setObjectName("label_66")
        self.listWidget_sqlmap_columns = QtWidgets.QListWidget(self.tab_14)
        self.listWidget_sqlmap_columns.setGeometry(QtCore.QRect(370, 130, 151, 271))
        self.listWidget_sqlmap_columns.setObjectName("listWidget_sqlmap_columns")
        self.label_67 = QtWidgets.QLabel(self.tab_14)
        self.label_67.setGeometry(QtCore.QRect(550, 110, 71, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.tab_14)
        self.label_68.setGeometry(QtCore.QRect(10, 410, 60, 16))
        self.label_68.setObjectName("label_68")
        self.plainTextEdit_sqlmap_result = QtWidgets.QPlainTextEdit(self.tab_14)
        self.plainTextEdit_sqlmap_result.setGeometry(QtCore.QRect(10, 430, 861, 321))
        self.plainTextEdit_sqlmap_result.setReadOnly(True)
        self.plainTextEdit_sqlmap_result.setObjectName("plainTextEdit_sqlmap_result")
        self.listWidget_sqlmap_tables = QtWidgets.QListWidget(self.tab_14)
        self.listWidget_sqlmap_tables.setGeometry(QtCore.QRect(190, 130, 151, 271))
        self.listWidget_sqlmap_tables.setObjectName("listWidget_sqlmap_tables")
        self.listWidget_sqlmap_dbs = QtWidgets.QListWidget(self.tab_14)
        self.listWidget_sqlmap_dbs.setGeometry(QtCore.QRect(10, 130, 151, 271))
        self.listWidget_sqlmap_dbs.setObjectName("listWidget_sqlmap_dbs")
        self.tableView_sqlmap_query = QtWidgets.QTableView(self.tab_14)
        self.tableView_sqlmap_query.setGeometry(QtCore.QRect(550, 130, 511, 271))
        self.tableView_sqlmap_query.setObjectName("tableView_sqlmap_query")
        self.label_69 = QtWidgets.QLabel(self.tab_14)
        self.label_69.setGeometry(QtCore.QRect(880, 410, 60, 16))
        self.label_69.setObjectName("label_69")
        self.plainTextEdit_sqlmap_sysinfo = QtWidgets.QPlainTextEdit(self.tab_14)
        self.plainTextEdit_sqlmap_sysinfo.setGeometry(QtCore.QRect(890, 430, 171, 321))
        self.plainTextEdit_sqlmap_sysinfo.setReadOnly(True)
        self.plainTextEdit_sqlmap_sysinfo.setObjectName("plainTextEdit_sqlmap_sysinfo")
        self.pushButton_sqlmap_kill = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_kill.setGeometry(QtCore.QRect(840, 5, 91, 32))
        self.pushButton_sqlmap_kill.setObjectName("pushButton_sqlmap_kill")
        self.pushButton_sqlmap_export = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_export.setGeometry(QtCore.QRect(750, 65, 91, 32))
        self.pushButton_sqlmap_export.setObjectName("pushButton_sqlmap_export")
        self.label_sqlmap_taskid = QtWidgets.QLabel(self.tab_14)
        self.label_sqlmap_taskid.setGeometry(QtCore.QRect(760, 110, 301, 16))
        self.label_sqlmap_taskid.setObjectName("label_sqlmap_taskid")
        self.pushButton_sqlmap_clearlog = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_sqlmap_clearlog.setGeometry(QtCore.QRect(750, 5, 91, 32))
        self.pushButton_sqlmap_clearlog.setObjectName("pushButton_sqlmap_clearlog")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_41 = QtWidgets.QLabel(self.tab_9)
        self.label_41.setGeometry(QtCore.QRect(11, 21, 74, 16))
        self.label_41.setObjectName("label_41")
        self.lineEdit_shodan_key = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_shodan_key.setEnabled(True)
        self.lineEdit_shodan_key.setGeometry(QtCore.QRect(93, 20, 371, 21))
        self.lineEdit_shodan_key.setObjectName("lineEdit_shodan_key")
        self.label_42 = QtWidgets.QLabel(self.tab_9)
        self.label_42.setGeometry(QtCore.QRect(20, 60, 51, 20))
        self.label_42.setObjectName("label_42")
        self.lineEdit_shodan_keyword = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_shodan_keyword.setGeometry(QtCore.QRect(93, 60, 371, 21))
        self.lineEdit_shodan_keyword.setObjectName("lineEdit_shodan_keyword")
        self.label_shodan_searchresult = QtWidgets.QLabel(self.tab_9)
        self.label_shodan_searchresult.setGeometry(QtCore.QRect(10, 100, 201, 16))
        self.label_shodan_searchresult.setObjectName("label_shodan_searchresult")
        self.tableView_shodan_searchresult = QtWidgets.QTableView(self.tab_9)
        self.tableView_shodan_searchresult.setGeometry(QtCore.QRect(10, 120, 1061, 192))
        self.tableView_shodan_searchresult.setShowGrid(True)
        self.tableView_shodan_searchresult.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView_shodan_searchresult.setSortingEnabled(False)
        self.tableView_shodan_searchresult.setWordWrap(True)
        self.tableView_shodan_searchresult.setCornerButtonEnabled(True)
        self.tableView_shodan_searchresult.setObjectName("tableView_shodan_searchresult")
        self.tableView_shodan_searchresult.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_shodan_searchresult.horizontalHeader().setHighlightSections(True)
        self.tableView_shodan_searchresult.verticalHeader().setSortIndicatorShown(False)
        self.listWidget_shodan_port = QtWidgets.QListWidget(self.tab_9)
        self.listWidget_shodan_port.setGeometry(QtCore.QRect(10, 340, 121, 411))
        self.listWidget_shodan_port.setObjectName("listWidget_shodan_port")
        self.label_44 = QtWidgets.QLabel(self.tab_9)
        self.label_44.setGeometry(QtCore.QRect(10, 320, 60, 16))
        self.label_44.setObjectName("label_44")
        self.textEdit_shodan_fullinfo = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_shodan_fullinfo.setGeometry(QtCore.QRect(140, 340, 671, 411))
        self.textEdit_shodan_fullinfo.setObjectName("textEdit_shodan_fullinfo")
        self.line = QtWidgets.QFrame(self.tab_9)
        self.line.setGeometry(QtCore.QRect(0, 90, 1081, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_46 = QtWidgets.QLabel(self.tab_9)
        self.label_46.setGeometry(QtCore.QRect(480, 20, 41, 16))
        self.label_46.setObjectName("label_46")
        self.lineEdit_shodan_ip = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_shodan_ip.setGeometry(QtCore.QRect(502, 20, 116, 21))
        self.lineEdit_shodan_ip.setObjectName("lineEdit_shodan_ip")
        self.pushButton_shodan_search = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_shodan_search.setGeometry(QtCore.QRect(630, 15, 113, 32))
        self.pushButton_shodan_search.setObjectName("pushButton_shodan_search")
        self.pushButton_shodan_clear = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_shodan_clear.setGeometry(QtCore.QRect(760, 15, 113, 32))
        self.pushButton_shodan_clear.setObjectName("pushButton_shodan_clear")
        self.layoutWidget10 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget10.setGeometry(QtCore.QRect(480, 60, 140, 26))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_8.addWidget(self.label_45)
        self.comboBox_shodan_city = QtWidgets.QComboBox(self.layoutWidget10)
        self.comboBox_shodan_city.setObjectName("comboBox_shodan_city")
        self.comboBox_shodan_city.addItem("")
        self.comboBox_shodan_city.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_shodan_city)
        self.label_49 = QtWidgets.QLabel(self.tab_9)
        self.label_49.setGeometry(QtCore.QRect(140, 320, 101, 16))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_9)
        self.label_50.setGeometry(QtCore.QRect(820, 510, 101, 16))
        self.label_50.setObjectName("label_50")
        self.plainTextEdit_shodan_log = QtWidgets.QPlainTextEdit(self.tab_9)
        self.plainTextEdit_shodan_log.setGeometry(QtCore.QRect(820, 530, 251, 221))
        self.plainTextEdit_shodan_log.setReadOnly(True)
        self.plainTextEdit_shodan_log.setObjectName("plainTextEdit_shodan_log")
        self.plainTextEdit_shodan_hostinfo = QtWidgets.QPlainTextEdit(self.tab_9)
        self.plainTextEdit_shodan_hostinfo.setGeometry(QtCore.QRect(820, 340, 251, 171))
        self.plainTextEdit_shodan_hostinfo.setObjectName("plainTextEdit_shodan_hostinfo")
        self.label_51 = QtWidgets.QLabel(self.tab_9)
        self.label_51.setGeometry(QtCore.QRect(820, 320, 101, 16))
        self.label_51.setObjectName("label_51")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.plainTextEdit_sshusername_result = QtWidgets.QPlainTextEdit(self.tab_10)
        self.plainTextEdit_sshusername_result.setGeometry(QtCore.QRect(10, 70, 1051, 661))
        self.plainTextEdit_sshusername_result.setReadOnly(True)
        self.plainTextEdit_sshusername_result.setObjectName("plainTextEdit_sshusername_result")
        self.progressBar_sshusername_progress = QtWidgets.QProgressBar(self.tab_10)
        self.progressBar_sshusername_progress.setGeometry(QtCore.QRect(10, 730, 1051, 23))
        self.progressBar_sshusername_progress.setProperty("value", 0)
        self.progressBar_sshusername_progress.setObjectName("progressBar_sshusername_progress")
        self.layoutWidget11 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget11.setGeometry(QtCore.QRect(0, 20, 1079, 33))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_12.addWidget(self.label_43)
        self.lineEdit_sshusername_ip = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_sshusername_ip.setObjectName("lineEdit_sshusername_ip")
        self.horizontalLayout_12.addWidget(self.lineEdit_sshusername_ip)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_12.addWidget(self.label_47)
        self.lineEdit_sshusername_port = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_sshusername_port.setObjectName("lineEdit_sshusername_port")
        self.horizontalLayout_12.addWidget(self.lineEdit_sshusername_port)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_12.addWidget(self.label_52)
        self.lineEdit_sshusername_username = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_sshusername_username.setObjectName("lineEdit_sshusername_username")
        self.horizontalLayout_12.addWidget(self.lineEdit_sshusername_username)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_12.addWidget(self.label_53)
        self.lineEdit_sshusername_usernamelist = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_sshusername_usernamelist.setObjectName("lineEdit_sshusername_usernamelist")
        self.horizontalLayout_12.addWidget(self.lineEdit_sshusername_usernamelist)
        self.pushButton_sshusername_selectfile = QtWidgets.QPushButton(self.layoutWidget11)
        self.pushButton_sshusername_selectfile.setObjectName("pushButton_sshusername_selectfile")
        self.horizontalLayout_12.addWidget(self.pushButton_sshusername_selectfile)
        self.pushButton_sshusername_start = QtWidgets.QPushButton(self.layoutWidget11)
        self.pushButton_sshusername_start.setObjectName("pushButton_sshusername_start")
        self.horizontalLayout_12.addWidget(self.pushButton_sshusername_start)
        self.pushButton_sshusername_stop = QtWidgets.QPushButton(self.layoutWidget11)
        self.pushButton_sshusername_stop.setObjectName("pushButton_sshusername_stop")
        self.horizontalLayout_12.addWidget(self.pushButton_sshusername_stop)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_54 = QtWidgets.QLabel(self.tab_11)
        self.label_54.setGeometry(QtCore.QRect(11, 25, 20, 16))
        self.label_54.setObjectName("label_54")
        self.lineEdit_slowhttp_ip = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_slowhttp_ip.setGeometry(QtCore.QRect(39, 24, 181, 21))
        self.lineEdit_slowhttp_ip.setObjectName("lineEdit_slowhttp_ip")
        self.label_56 = QtWidgets.QLabel(self.tab_11)
        self.label_56.setGeometry(QtCore.QRect(360, 25, 61, 18))
        self.label_56.setObjectName("label_56")
        self.comboBox_slowhttp_thread = QtWidgets.QComboBox(self.tab_11)
        self.comboBox_slowhttp_thread.setGeometry(QtCore.QRect(410, 22, 91, 26))
        self.comboBox_slowhttp_thread.setObjectName("comboBox_slowhttp_thread")
        self.comboBox_slowhttp_thread.addItem("")
        self.comboBox_slowhttp_thread.addItem("")
        self.comboBox_slowhttp_thread.addItem("")
        self.comboBox_slowhttp_thread.addItem("")
        self.label_57 = QtWidgets.QLabel(self.tab_11)
        self.label_57.setGeometry(QtCore.QRect(230, 25, 30, 18))
        self.label_57.setObjectName("label_57")
        self.lineEdit_slowhttp_port = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_slowhttp_port.setGeometry(QtCore.QRect(270, 24, 71, 21))
        self.lineEdit_slowhttp_port.setObjectName("lineEdit_slowhttp_port")
        self.pushButton_slowhttp_start = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_slowhttp_start.setGeometry(QtCore.QRect(620, 20, 68, 32))
        self.pushButton_slowhttp_start.setObjectName("pushButton_slowhttp_start")
        self.pushButton_slowhttp_stop = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_slowhttp_stop.setGeometry(QtCore.QRect(690, 20, 68, 32))
        self.pushButton_slowhttp_stop.setObjectName("pushButton_slowhttp_stop")
        self.plainTextEdit_slowhttp_result = QtWidgets.QPlainTextEdit(self.tab_11)
        self.plainTextEdit_slowhttp_result.setGeometry(QtCore.QRect(10, 60, 1051, 691))
        self.plainTextEdit_slowhttp_result.setObjectName("plainTextEdit_slowhttp_result")
        self.label_58 = QtWidgets.QLabel(self.tab_11)
        self.label_58.setGeometry(QtCore.QRect(510, 25, 51, 16))
        self.label_58.setObjectName("label_58")
        self.comboBox_slowhttp_time = QtWidgets.QComboBox(self.tab_11)
        self.comboBox_slowhttp_time.setGeometry(QtCore.QRect(550, 22, 61, 26))
        self.comboBox_slowhttp_time.setObjectName("comboBox_slowhttp_time")
        self.comboBox_slowhttp_time.addItem("")
        self.comboBox_slowhttp_time.addItem("")
        self.comboBox_slowhttp_time.addItem("")
        self.comboBox_slowhttp_time.addItem("")
        self.comboBox_slowhttp_time.addItem("")
        self.tabWidget.addTab(self.tab_11, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_70.setText(_translate("MainWindow", "目标ip:"))
        self.label_71.setText(_translate("MainWindow", "目标端口:"))
        self.label_72.setText(_translate("MainWindow", "执行命令:"))
        self.comboBox_windows_comboBox.setItemText(0, _translate("MainWindow", "CVE-2020-0796"))
        self.comboBox_windows_comboBox.setItemText(1, _translate("MainWindow", "MS17010"))
        self.label_73.setText(_translate("MainWindow", "选择漏洞:"))
        self.plainTextEdit_windows_result.setPlainText(_translate("MainWindow", "目前该功能仅支持poc测试，若检测出存在漏洞，请移步kali进行利用。"))
        self.pushButton_windows_scan.setText(_translate("MainWindow", "探测"))
        self.pushButton_windows_exe.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Windows"))
        self.plainTextEdit_weblogic_result.setPlainText(_translate("MainWindow", "目前扫描支持：\n"
"WeblogicConsole,CVE-2014-4210,CVE-2019-2725,CVE-2019-2729,CVE-2017-10271,CVE-2017-3506,CVE-2019-2618,CVE-2018-2894，CVE-2018-2628,CVE-2018-2893,CVE-2016-0638,CVE-2016-3510,CVE-2017-3248,CVE-2020-14882\n"
"命令执行支持：\n"
"CVE-2019-2725,CVE-2020-14882"))
        self.label.setText(_translate("MainWindow", "目标ip："))
        self.label_2.setText(_translate("MainWindow", "目标port："))
        self.pushButton_weblogic_start.setText(_translate("MainWindow", "start"))
        self.label_23.setText(_translate("MainWindow", "选择漏洞："))
        self.comboBox_weblogic_bug.setItemText(0, _translate("MainWindow", "CVE-2019-2725"))
        self.comboBox_weblogic_bug.setItemText(1, _translate("MainWindow", "CVE-2020-14882"))
        self.label_3.setText(_translate("MainWindow", "执行命令："))
        self.pushButton_weblogic_exe.setText(_translate("MainWindow", "命令执行"))
        self.pushButton_weblogic_uploadshell.setText(_translate("MainWindow", "上传shell"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "weblogic"))
        self.label_6.setText(_translate("MainWindow", "struts2漏洞扫描及利用："))
        self.label_7.setText(_translate("MainWindow", "目标url："))
        self.label_8.setText(_translate("MainWindow", "cookie："))
        self.pushButton_struts2_scan.setText(_translate("MainWindow", "扫描"))
        self.plainTextEdit_struts2_result.setPlainText(_translate("MainWindow", "扫描：\n"
"ST2-005、ST2-008-1、ST2-008-2、ST2-009、ST2-013、ST2-015、ST2-016、ST2-019、ST2-devmode、ST2-032、ST2-033、ST2-037、ST-045-1、ST045-2、ST-046、ST2-048、ST2-052、ST2-053、struts2-057-1、struts2-057-2\n"
"命令执行：\n"
"struts2-005、struts2-008-1、struts2-008-2、struts2-009、struts2-013、struts2-015、struts2-016、struts2-019、struts2-devmode、struts2-032、struts2-033、struts2-037、struts2-045-1、struts2-045-2、struts2-046、struts2-048、struts2-052、struts2-057-1、struts2-057-2"))
        self.comboBox_strust2_bug.setItemText(0, _translate("MainWindow", "struts2-005"))
        self.comboBox_strust2_bug.setItemText(1, _translate("MainWindow", "struts2-008-1"))
        self.comboBox_strust2_bug.setItemText(2, _translate("MainWindow", "struts2-008-2"))
        self.comboBox_strust2_bug.setItemText(3, _translate("MainWindow", "struts2-009"))
        self.comboBox_strust2_bug.setItemText(4, _translate("MainWindow", "struts2-013"))
        self.comboBox_strust2_bug.setItemText(5, _translate("MainWindow", "struts2-015"))
        self.comboBox_strust2_bug.setItemText(6, _translate("MainWindow", "struts2-016"))
        self.comboBox_strust2_bug.setItemText(7, _translate("MainWindow", "struts2-019"))
        self.comboBox_strust2_bug.setItemText(8, _translate("MainWindow", "struts2-devmode"))
        self.comboBox_strust2_bug.setItemText(9, _translate("MainWindow", "struts2-032"))
        self.comboBox_strust2_bug.setItemText(10, _translate("MainWindow", "struts2-033"))
        self.comboBox_strust2_bug.setItemText(11, _translate("MainWindow", "struts2-037"))
        self.comboBox_strust2_bug.setItemText(12, _translate("MainWindow", "struts2-045-1"))
        self.comboBox_strust2_bug.setItemText(13, _translate("MainWindow", "struts2-045-2"))
        self.comboBox_strust2_bug.setItemText(14, _translate("MainWindow", "struts2-046"))
        self.comboBox_strust2_bug.setItemText(15, _translate("MainWindow", "struts2-048"))
        self.comboBox_strust2_bug.setItemText(16, _translate("MainWindow", "struts2-057-1"))
        self.comboBox_strust2_bug.setItemText(17, _translate("MainWindow", "struts2-057-2"))
        self.pushButton_struts2_exe.setText(_translate("MainWindow", "执行！"))
        self.label_10.setText(_translate("MainWindow", "执行命令："))
        self.label_9.setText(_translate("MainWindow", "选择漏洞："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "strust2"))
        self.pushButton_jboss_scan.setText(_translate("MainWindow", "扫描"))
        self.label_121.setText(_translate("MainWindow", "cmd:"))
        self.label_122.setText(_translate("MainWindow", "url:"))
        self.comboBox_jboss_cve.setItemText(0, _translate("MainWindow", "CVE-2017-12149"))
        self.pushButton_jboss_exe.setText(_translate("MainWindow", "执行"))
        self.pushButton_jboss_urllist.setText(_translate("MainWindow", "url列表"))
        self.label_123.setText(_translate("MainWindow", "选择cve:"))
        self.lineEdit_jboss_urllist.setText(_translate("MainWindow", "若填写url则本项不生效"))
        self.plainTextEdit_jboss_result.setPlainText(_translate("MainWindow", "本模块需要安装java运行环境才可使用。\n"
"1、选择ysoserial.jar路径，本工具根目录下我放入了一个\n"
"2、输入url或者选择url列表\n"
"3、扫描\n"
"4、若扫描存在漏洞，选择对应的cve编号进行命令执行"))
        self.pushButton_jboss_ysoserialpath.setText(_translate("MainWindow", "ysoserial.jar路径"))
        self.pushButton_jboss_clearlog.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "jboss"))
        self.label_55.setText(_translate("MainWindow", "url:"))
        self.label_59.setText(_translate("MainWindow", "cmd:"))
        self.comboBox_apache_cve.setItemText(0, _translate("MainWindow", "CVE-2019-0193"))
        self.label_60.setText(_translate("MainWindow", "选择cve:"))
        self.pushButton_apache_scan.setText(_translate("MainWindow", "扫描"))
        self.pushButton_apache_exe.setText(_translate("MainWindow", "执行"))
        self.plainTextEdit_apache_result.setPlainText(_translate("MainWindow", "1、输入url或者从文件读取url列表\n"
"2、扫描\n"
"3、若扫描出存在漏洞，选择对应漏洞进行命令执行"))
        self.pushButton_apache_selectfile.setText(_translate("MainWindow", "文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "apache"))
        self.label_74.setText(_translate("MainWindow", "ip地址:"))
        self.label_75.setText(_translate("MainWindow", "port:"))
        self.lineEdit_tomcat_2020_1938_port.setText(_translate("MainWindow", "8009"))
        self.label_76.setText(_translate("MainWindow", "文件路径:"))
        self.lineEdit_tomcat_2020_1938_file_path.setText(_translate("MainWindow", "/WEB-INF/web.xml"))
        self.pushButton_tomcat_2020_1938_read_file.setText(_translate("MainWindow", "读取"))
        self.plainTextEdit_tomcat_2020_1938_result.setPlainText(_translate("MainWindow", "ip:目标ip\n"
"port:ajp协议端口，默认8009\n"
"ip地址列表：仅供检测使用，当ip地址栏有值时，该部分失效\n"
"文件路径:要读取或者执行的文件路径"))
        self.label_77.setText(_translate("MainWindow", "ip地址列表:"))
        self.pushButton_tomcat_2020_1938_check.setText(_translate("MainWindow", "检测"))
        self.pushButton_tomcat_2020_1938_select_file.setText(_translate("MainWindow", "选择"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_18), _translate("MainWindow", "CVE-2020-1938"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), _translate("MainWindow", ".."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("MainWindow", "tomcat"))
        self.label_11.setText(_translate("MainWindow", "web路径探测，默认使用字典dict/url_index.txt"))
        self.label_12.setText(_translate("MainWindow", "目标url:"))
        self.label_13.setText(_translate("MainWindow", "cookie:"))
        self.label_14.setText(_translate("MainWindow", "字典路径："))
        self.label_15.setText(_translate("MainWindow", "线程数："))
        self.comboBox_urlscan_thread.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_urlscan_thread.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_urlscan_thread.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_urlscan_thread.setItemText(3, _translate("MainWindow", "35"))
        self.plainTextEdit_urlscan_result.setPlainText(_translate("MainWindow", "1、输入目标url\n"
"2、若目标使用了友好的404页面，请自行提取页面特征填入到不理页面包含内容\n"
"3、选择字典路径，本工具根目录下自带目录扫描字典。\n"
"4、选择线程\n"
"5、开始扫描"))
        self.label_48.setText(_translate("MainWindow", "不理睬页面包含内容:"))
        self.pushButton_urlscan_choice.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_urlscan_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_urlscan_stop.setText(_translate("MainWindow", "暂停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "目录扫描"))
        self.label_16.setText(_translate("MainWindow", "ip："))
        self.label_17.setText(_translate("MainWindow", "port："))
        self.plainTextEdit_brute_result.setPlainText(_translate("MainWindow", "    您可以选择直接输入ip，也可以选择导入一个列表文件，如果您输入了ip则下方ip列表失效，但是port是必须的，可以选择协议类型进行爆破，用户名与密码字典默认在dict/brute_username.txt 和 dict/brute_passwd.txt 也可以使用导入的字典，您可以通过选择文件来设置字典，也可以在后方文本输入框输入字典路径。"))
        self.label_18.setText(_translate("MainWindow", "协议类型："))
        self.radioButton_brute_ftp.setText(_translate("MainWindow", "FTP"))
        self.radioButton_brute_mysql.setText(_translate("MainWindow", "MYSQL"))
        self.label_19.setText(_translate("MainWindow", "线程数："))
        self.comboBox_brute_thread.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_brute_thread.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_brute_thread.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_brute_thread.setItemText(3, _translate("MainWindow", "35"))
        self.radioButton_brute_ssh.setText(_translate("MainWindow", "SSH"))
        self.label_20.setText(_translate("MainWindow", "ip列表："))
        self.pushButton_brute_set_iplist.setText(_translate("MainWindow", "请选择文件"))
        self.label_21.setText(_translate("MainWindow", "用户名列表："))
        self.pushButton_brute_set_usernamelist.setText(_translate("MainWindow", "请选择文件"))
        self.label_22.setText(_translate("MainWindow", "密码列表："))
        self.pushButton_brute_set_passwdlist.setText(_translate("MainWindow", "请选择文件"))
        self.pushButton_brute_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_brute_stop.setText(_translate("MainWindow", "暂停"))
        self.radioButton_brute_telnet.setText(_translate("MainWindow", "Telnet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "暴力破解"))
        self.plainTextEdit_portscan_result.setPlainText(_translate("MainWindow", "ip地址格式192.168.1.1或者192.168.1.1-255。\n"
"端口的格式可以自己输入21,22,80，以逗号隔开，也可以使用1-1000这种格式，或者选择后面的单选按钮。"))
        self.label_4.setText(_translate("MainWindow", "ip地址："))
        self.pushButton_portscan_selectfile.setText(_translate("MainWindow", "文件"))
        self.label_5.setText(_translate("MainWindow", "端口列表："))
        self.radioButton_portscan_radio1000.setText(_translate("MainWindow", "top1000"))
        self.radioButton_portscan_radioall.setText(_translate("MainWindow", "全端口"))
        self.label_24.setText(_translate("MainWindow", "线程数:"))
        self.comboBox_portscan_thread.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_portscan_thread.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_portscan_thread.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_portscan_thread.setItemText(3, _translate("MainWindow", "35"))
        self.pushButton_portscan_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_portscan_stop.setText(_translate("MainWindow", "暂停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "端口扫描"))
        self.plainTextEdit_submain_result.setPlainText(_translate("MainWindow", "  域名处输入要爆破的域名，例如baidu.com，若要使用自己的子域名字典，请点击选择进行选择，本工具自带的域名字典在dict目录下。\n"
"  当处在内网环境时，要使用本功能需要自定义dns，输入自定义dns后，下拉框dns失效，采用输入的dns。"))
        self.label_28.setText(_translate("MainWindow", "字典："))
        self.lineEdit_subdomian_dict.setText(_translate("MainWindow", "dict/subdomain.txt"))
        self.label_25.setText(_translate("MainWindow", "域名："))
        self.label_26.setText(_translate("MainWindow", "dns："))
        self.comboBox_subdomain_dns.setItemText(0, _translate("MainWindow", "114.114.114.114"))
        self.comboBox_subdomain_dns.setItemText(1, _translate("MainWindow", "114.114.115.115"))
        self.comboBox_subdomain_dns.setItemText(2, _translate("MainWindow", "223.5.5.5"))
        self.comboBox_subdomain_dns.setItemText(3, _translate("MainWindow", "223.6.6.6"))
        self.comboBox_subdomain_dns.setItemText(4, _translate("MainWindow", "180.76.76.76"))
        self.comboBox_subdomain_dns.setItemText(5, _translate("MainWindow", "119.29.29.29"))
        self.comboBox_subdomain_dns.setItemText(6, _translate("MainWindow", "182.254.116.116"))
        self.comboBox_subdomain_dns.setItemText(7, _translate("MainWindow", "210.2.4.8"))
        self.comboBox_subdomain_dns.setItemText(8, _translate("MainWindow", "112.124.47.27"))
        self.comboBox_subdomain_dns.setItemText(9, _translate("MainWindow", "114.215.126.16"))
        self.comboBox_subdomain_dns.setItemText(10, _translate("MainWindow", "101.226.4.6"))
        self.comboBox_subdomain_dns.setItemText(11, _translate("MainWindow", "218.30.118.6"))
        self.comboBox_subdomain_dns.setItemText(12, _translate("MainWindow", "8.8.8.8"))
        self.comboBox_subdomain_dns.setItemText(13, _translate("MainWindow", "8.8.4.4"))
        self.label_29.setText(_translate("MainWindow", "自定义dns："))
        self.label_27.setText(_translate("MainWindow", "线程数："))
        self.comboBox_subdomain_thread.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_subdomain_thread.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_subdomain_thread.setItemText(2, _translate("MainWindow", "10"))
        self.pushButton_subdomian_selectdict.setText(_translate("MainWindow", "选择"))
        self.pushButton_subdomain_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_subdomain_stop.setText(_translate("MainWindow", "暂停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "子域名爆破"))
        self.plainTextEdit_unauthorized_data1request.setPlainText(_translate("MainWindow", "数据包1 request"))
        self.plainTextEdit_unauthorized_data2request.setPlainText(_translate("MainWindow", "数据包2 request\n"
""))
        self.plainTextEdit_unauthorized_result.setPlainText(_translate("MainWindow", "1、复制粘贴想要进行越权测试的数据包分别到request1、request2\n"
"2、点击识别参数工具会将所有参数是被出来自动填入参数框\n"
"3、选择越权关键特征\n"
"4、选择越权对应关键字\n"
"5、点击全部探测，工具将会对所有参数进行越权探测\n"
"6、等待返回结果"))
        self.label_31.setText(_translate("MainWindow", "POST:"))
        self.label_32.setText(_translate("MainWindow", "COOKIE:"))
        self.label_30.setText(_translate("MainWindow", "GET:"))
        self.radioButton_unauthorized_vertical.setText(_translate("MainWindow", "垂直越权"))
        self.label_33.setText(_translate("MainWindow", "选择特征:"))
        self.label_34.setText(_translate("MainWindow", "response1:"))
        self.label_35.setText(_translate("MainWindow", "response2:"))
        self.pushButton_unauthorized_allparam.setText(_translate("MainWindow", "识别参数"))
        self.pushButton_unauthorized_clearresult.setText(_translate("MainWindow", "清空日志"))
        self.pushButton_unauthorized_startallparam.setText(_translate("MainWindow", "全部探测"))
        self.radioButton_unauthorized_operation.setText(_translate("MainWindow", "越权操作"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "越权探测"))
        self.plainTextEdit_xss_request.setPlainText(_translate("MainWindow", "request"))
        self.plainTextEdit_xss_result.setPlainText(_translate("MainWindow", "注意事项：若返回中有不只一个的返回点，且当受到的过滤不同时，有几率使payload的制作出现偏差，届时插入数据包后请稍加调整\n"
"1、输入要进行XSS探测的数据包\n"
"2、点击开始\n"
"3、查看payload"))
        self.plainTextEdit_xss_payload.setPlainText(_translate("MainWindow", "payload:"))
        self.label_36.setText(_translate("MainWindow", "线程数:"))
        self.comboBox_xss_thread.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_xss_thread.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_xss_thread.setItemText(2, _translate("MainWindow", "10"))
        self.comboBox_xss_thread.setItemText(3, _translate("MainWindow", "20"))
        self.label_37.setText(_translate("MainWindow", "延时:"))
        self.comboBox_xss_delay.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_xss_delay.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_xss_delay.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_xss_delay.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_xss_delay.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_xss_delay.setItemText(5, _translate("MainWindow", "5"))
        self.label_38.setText(_translate("MainWindow", "跳过DOM:"))
        self.comboBox_xss_skipdom.setItemText(0, _translate("MainWindow", "是"))
        self.comboBox_xss_skipdom.setItemText(1, _translate("MainWindow", "否"))
        self.label_39.setText(_translate("MainWindow", "边爬边扫:"))
        self.comboBox_xss_crawl.setItemText(0, _translate("MainWindow", "否"))
        self.comboBox_xss_crawl.setItemText(1, _translate("MainWindow", "是"))
        self.label_40.setText(_translate("MainWindow", "爬行深度:"))
        self.comboBox_xss_deep.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_xss_deep.setItemText(1, _translate("MainWindow", "3"))
        self.comboBox_xss_deep.setItemText(2, _translate("MainWindow", "4"))
        self.pushButton_xss_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_xss_wait.setText(_translate("MainWindow", "暂停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "XSS跨站脚本攻击"))
        self.label_61.setText(_translate("MainWindow", "sqlmapapi地址:"))
        self.lineEdit_sqlmap_apiurl.setText(_translate("MainWindow", "http://127.0.0.1:8775"))
        self.pushButton_sqlmap_checkenv.setText(_translate("MainWindow", "检测环境"))
        self.label_62.setText(_translate("MainWindow", "要注入数据包文件路径:"))
        self.label_63.setText(_translate("MainWindow", "执行sql语句:"))
        self.pushButton_sqlmap_selectfile.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_sqlmap_startscan.setText(_translate("MainWindow", "Go!"))
        self.pushButton_sqlmap_exesql.setText(_translate("MainWindow", "Go!"))
        self.label_64.setText(_translate("MainWindow", "库："))
        self.label_65.setText(_translate("MainWindow", "表："))
        self.label_66.setText(_translate("MainWindow", "列："))
        self.label_67.setText(_translate("MainWindow", "查询结果:"))
        self.label_68.setText(_translate("MainWindow", "日志:"))
        self.plainTextEdit_sqlmap_result.setPlainText(_translate("MainWindow", "1、本工具根目录下自带sqlmap，进入目录命令行下输入：python3 sqlmapapi.py -s\n"
"2、选择需要探测注入的数据包\n"
"3、点击Go！进行探测是否存在注入\n"
"4、若存在注入下方库会自动读取，系统信息会有提示\n"
"5、点击库显示表\n"
"6、点击表显示列\n"
"7、选择想要查询的数据，使用执行sql语句来查询，会在查询结果处返回结果。\n"
"\n"
"--部分功能还未实现，有时间会慢慢优化"))
        self.label_69.setText(_translate("MainWindow", "系统信息:"))
        self.pushButton_sqlmap_kill.setText(_translate("MainWindow", "终止任务"))
        self.pushButton_sqlmap_export.setText(_translate("MainWindow", "导出结果"))
        self.label_sqlmap_taskid.setText(_translate("MainWindow", "当前taskid:"))
        self.pushButton_sqlmap_clearlog.setText(_translate("MainWindow", "清空日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("MainWindow", "sqlmap"))
        self.label_41.setText(_translate("MainWindow", "shodan key:"))
        self.lineEdit_shodan_key.setText(_translate("MainWindow", "Shu5SI10Gxx0ojmMG0k7sjSulesVBtoI"))
        self.label_42.setText(_translate("MainWindow", "关键字:"))
        self.label_shodan_searchresult.setText(_translate("MainWindow", "搜索IP结果:"))
        self.label_44.setText(_translate("MainWindow", "端口:"))
        self.label_46.setText(_translate("MainWindow", "ip:"))
        self.pushButton_shodan_search.setText(_translate("MainWindow", "搜索"))
        self.pushButton_shodan_clear.setText(_translate("MainWindow", "清空"))
        self.label_45.setText(_translate("MainWindow", "地区:"))
        self.comboBox_shodan_city.setItemText(0, _translate("MainWindow", "NULL"))
        self.comboBox_shodan_city.setItemText(1, _translate("MainWindow", "CN"))
        self.label_49.setText(_translate("MainWindow", "详细信息:"))
        self.label_50.setText(_translate("MainWindow", "日志:"))
        self.plainTextEdit_shodan_log.setPlainText(_translate("MainWindow", "本工具连接shodan进行网络设备检索\n"
"1、输入shodan key不知道如何获取请百度\n"
"2、输入关键字或者ip，若输入了ip则关键字失效\n"
"3、点击搜索ip结果列表中的记录，会自动加在选中主机开放的端口\n"
"4、点击端口列表，会自动显示该端口的详细信息\n"
"\n"
"--shodan的连接速度不敢恭维，各位要耐心的等"))
        self.label_51.setText(_translate("MainWindow", "主机信息:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "shodan"))
        self.plainTextEdit_sshusername_result.setPlainText(_translate("MainWindow", "通过利用openssh的用户名枚举漏洞而实现的自动化工具\n"
"1、输入ip、port\n"
"2、给定一个用户名或者用户名字典\n"
"3、工具会给出验证存在的用户名"))
        self.label_43.setText(_translate("MainWindow", "ip:"))
        self.label_47.setText(_translate("MainWindow", "port:"))
        self.label_52.setText(_translate("MainWindow", "用户名:"))
        self.label_53.setText(_translate("MainWindow", "用户名列表:"))
        self.pushButton_sshusername_selectfile.setText(_translate("MainWindow", "选择"))
        self.pushButton_sshusername_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_sshusername_stop.setText(_translate("MainWindow", "暂停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "SSH枚举用户名"))
        self.label_54.setText(_translate("MainWindow", "ip:"))
        self.label_56.setText(_translate("MainWindow", "连接数:"))
        self.comboBox_slowhttp_thread.setItemText(0, _translate("MainWindow", "200"))
        self.comboBox_slowhttp_thread.setItemText(1, _translate("MainWindow", "300"))
        self.comboBox_slowhttp_thread.setItemText(2, _translate("MainWindow", "400"))
        self.comboBox_slowhttp_thread.setItemText(3, _translate("MainWindow", "500"))
        self.label_57.setText(_translate("MainWindow", "端口:"))
        self.pushButton_slowhttp_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_slowhttp_stop.setText(_translate("MainWindow", "取消"))
        self.plainTextEdit_slowhttp_result.setPlainText(_translate("MainWindow", "采用慢速拒绝服务攻击的基本原理编写的dos工具\n"
"1、输入ip、port\n"
"2、选择连接数\n"
"3、开始dos"))
        self.label_58.setText(_translate("MainWindow", "间隔:"))
        self.comboBox_slowhttp_time.setItemText(0, _translate("MainWindow", "10"))
        self.comboBox_slowhttp_time.setItemText(1, _translate("MainWindow", "15"))
        self.comboBox_slowhttp_time.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_slowhttp_time.setItemText(3, _translate("MainWindow", "25"))
        self.comboBox_slowhttp_time.setItemText(4, _translate("MainWindow", "30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "慢速攻击"))
